apiVersion: v1
kind: Namespace
metadata:
  name: app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: survey-app-dev
data:
  SECRET_MANAGER_NAME: rds!db-7b7fc848-82ea-46e5-abb5-2c9128e4bbac

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: survey-app-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::779403607170:role/survery-app-backend-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: survey-app-dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: backend
          image: 779403607170.dkr.ecr.ap-south-1.amazonaws.com/backend:latest

          ports:
            - containerPort: 8000

          env:
            - name: SECRET_MANAGER_NAME_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SECRET_MANAGER_NAME

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: survey-app-dev

spec:
  type: ClusterIP

  selector:
    app: backend

  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: survey-app-dev

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: survey-app
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-south-1:779403607170:certificate/12345678-1234-1234-1234-123456789012"
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /api/*
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
