name: Backend CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

env:
  ECR_REPOSITORY: backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::779403607170:role/GithubActionsAssumeRole
          aws-region: ${{ vars.AWS_REGION }}

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories \
            --repository-names ${{ env.ECR_REPOSITORY }} \
          || \
          aws ecr create-repository \
            --repository-name ${{ env.ECR_REPOSITORY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image Info
        id: image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          echo "IMAGE=${IMAGE_URI}"
          echo "image=${IMAGE_URI}" >> $GITHUB_OUTPUT