name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Terraform folder to apply"
        required: true
        type: choice
        options:
          - infrastructure
          - deployment

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: arn:aws:iam::779403607170:role/GithubActionsAssumeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: terraform/dev/${{ github.event.inputs.folder }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: terraform/dev/${{ github.event.inputs.folder }}
        run: terraform validate

      - name: Terraform Plan (recreate plan before apply)
        working-directory: terraform/dev/${{ github.event.inputs.folder }}
        run: terraform plan -out=tfplan -var-file=../terraform.tfvars

      - name: Terraform Apply
        working-directory: terraform/dev/${{ github.event.inputs.folder }}
        run: terraform apply -auto-approve tfplan
